if [ -z ${WORKSPACE+x} ]; then
    PATH_SELF=$( cd "$( dirname "$0" )" && pwd )
    PROJECT_DIR=$PATH_SELF/..
else
    PROJECT_DIR=$WORKSPACE
fi

TARGET_DIR=$PROJECT_DIR/target
REPORTS_DIR=$TARGET_DIR/reports
COVERAGE_DIR=$REPORTS_DIR/coverage
COVERAGE_HTML_DIR=$COVERAGE_DIR/html
COVERAGE_XML_DIR=$COVERAGE_DIR/xml
COVERAGE_ANNOTATIONS_DIR=$COVERAGE_DIR/annotations
DIST_DIR=$TARGET_DIR/dist
PYENV_DIR=$TARGET_DIR/pyenv
BUILD_DIR=$PROJECT_DIR/build
DEBIAN_CFG_DIR=$PROJECT_DIR/building/debian
