#!/bin/sh



echo '    ___       ___       ___       ___       ___       ___   '
echo '   /\  \     /\  \     /\  \     /\__\     /\  \     /\__\  '
echo '  /::\  \   /::\  \   _\:\  \   /:/ _/_   /::\  \   /:| _|_ '
echo ' /::\:\__\ /\:\:\__\ /\/::\__\ /::-"\__\ /:/\:\__\ /::|/\__\'
echo ' \/\::/  / \:\:\/__/ \::/\/__/ \;:;-",-" \:\/:/  / \/|::/  /'
echo '    \/__/   \::/  /   \:\__\    |:|  |    \::/  /    |:/  / ' 
echo '             \/__/     \/__/     \|__|     \/__/     \/__/  '

ln -s /usr/bin/psistats /etc/init.d/psistats
ln -s /usr/share/psistats/psistats.conf /etc/psistats.conf
update-rc.d psistats defaults



